### Information Retrieval   |    Assignment 1-B

In [7]:
import pandas as pd
import numpy as np
import sys
import os
import random as rnd
import time
from collections import defaultdict
from functools import reduce
import math
from scipy import stats
import itertools

In [10]:
# Open file    
fileHandler = open ('YandexRelPredChallenge.txt', "r")
# Get list of all lines in file
listOfLines = fileHandler.readlines()
# Close file 
fileHandler.close()
#Empty frame to fill in
index=[x for x in range(0,100000)]
df = pd.DataFrame(index=index, columns=['SessionID', 'TimePassed',
                 'TypeOfAction', 'QueryID','RegionID', 'ListOfURLs', 'URLID'])
df.name='data'

# Iterate over the lines and fill in the dataframe
for ind, line in zip(index, listOfLines):
#     print('index')
    line = line.strip().split()
    if line[2]=='Q':

        df.loc[ind] = pd.Series({'SessionID':line[0], 'TimePassed':line[1], 'TypeOfAction':line[2],
                                     'QueryID':line[3],'RegionID':line[4], 'ListOfURLs':line[5:], 'URLID':np.nan})
    else:
        df.loc[ind] = pd.Series({'SessionID':line[0], 'TimePassed':line[1], 'TypeOfAction':line[2],
                                     'QueryID':np.nan,'RegionID':np.nan, 'ListOfURLs':np.nan, 'URLID':line[3:]})

In [11]:
# Getting the types right. 
df.SessionID = df.SessionID.astype(int)
df.TimePassed = df.TimePassed.astype(int)
df.TypeOfAction = df.TypeOfAction.astype(str)
df.RegionID = df.RegionID.astype(float)
df.TimePassed = df.TimePassed.astype(float)
def parse_ulrid(x):
    if type(x)==list:
        return x[0]
    else:
        return x
df.URLID = df.URLID.apply(parse_ulrid)
df.URLID = df.URLID.astype(float)

### Step 1:

Create new relevance:

So lets say that our experimental system is what Yandex return as a list now. Production or the system that is going to 'suck' (sort of a dumb system that we are going to compare against) will be constructed as shuffling each ranking for a query. 

Now, other approach, probably the better one: take the initial order as the 'benchmark' create only list of 0,1 (relevnace scores) for each system.
    - remember that we are interested only in three [3] first results.

In [12]:
# Create new relevance scores 
relevances = [0,1]
doc_length = 3 
MODELS =["E","P"]
relevance_pairs=["".join(seq) for seq in itertools.product("01", repeat=6)]
relevance_pairs = [(p[:3],p[3:])for p in relevance_pairs]

### Step 2: Calculate ERR

In [13]:
def ERR(l):
    theta = [ (2**i - 1)/(2) for i in [0,1]]
    err=0
    
    for rank in range(len(l)):
        prod = 1
        for idx in range(rank):
            prod*=(1-theta[int(l[idx])])
        prod*=(1/(rank+1))*theta[int(l[rank])]
        err+=prod
    return err


see the formuala for ERR at: http://olivier.chapelle.cc/pub/err.pdf

Get the deltas

In [14]:
binned = { x/100:[]for x in range(10,100,5) }#all below 0.05 is discarded The numbers are the upperbound
for tup in relevance_pairs:
    d_err = ERR(tup[0]) - ERR(tup[1])
    if d_err<0.05:
        continue #discard this entry
    
    d_err =int(5 * round((d_err*100)/5))/100
    binned[d_err].append(tup)

### Step 3

In [15]:
def create_possible_permutations(tup):
    ids=['a','b','c','d','e','f']
    pair1 = ['a','b','c']
    rel1  = tup[0]
    rel2  = tup[1]
    possible_pairs = []
    
    possible_ids = []
    for idx in range(3):
        possible_ids.append([(ids[idx+3],rel2[idx])])
        for _id,r1 in enumerate(rel1):
                if r1==rel2[idx]:
                    possible_ids[idx].append((ids[_id],rel2[idx]))#find all possible overlapping results
    
    for l0 in possible_ids[0]:
        for l1 in possible_ids[1]:
            for l2 in possible_ids[2]:
                if l0 is not l1 is not l2 is not l0:
                    possible_pairs.append([l0,l1,l2])
    pairs = []
    for p in possible_pairs:
        pairs.append(([ tup for tup in zip(pair1,rel1)],p))
    return pairs

In [16]:
def team_draft(tup,start=0,):
    l = []
    tup = (list(tup[0]),list(tup[1]))
    for idx in range(6):
        start+=1
        if len(tup[start%2])==0:continue
        elem = tup[start%2].pop(0)
        tup = (list(filter(lambda a: a != elem, tup[0])), list(filter(lambda a: a != elem, tup[1])))
        l.append((elem +(MODELS[start%2],)))
    return l

def probabelistic_interleaving(tup):
    l = []
    tup = (list(tup[0]),list(tup[1]))

    for x in range(6):
        active=[]
        if(len(tup[0]))>0:active+=[0]
        if(len(tup[1]))>0:active+=[1]    
        if not active:break
        cur = np.random.choice(active)#get the currently selected model
        
        unnormalized_probs=[]
        for idx in range(len(tup[cur])):
            unnormalized_probs.append(1/((idx+1)**3))#tau is 3 from the paper
        unnormalized_probs = [x/sum(unnormalized_probs) for x in unnormalized_probs]
        elemz_idx = np.random.choice(range(len(tup[cur])),p=unnormalized_probs)
        elem = tup[cur][idx]
        
        tup = (list(filter(lambda a: a != elem, tup[0])), list(filter(lambda a: a != elem, tup[1])))
        l.append((elem + (MODELS[cur],)))
    return l

In [17]:
l = create_possible_permutations(['111','111'])
print(probabelistic_interleaving(l[10]))
print(team_draft(l[10]))

[('c', '1', 'E'), ('b', '1', 'E'), ('d', '1', 'P'), ('a', '1', 'E')]
[('d', '1', 'P'), ('a', '1', 'E'), ('b', '1', 'P'), ('c', '1', 'E')]


### Step 4.1: Estimating the params of click models: Random Click Model

In [18]:
# Get all the doc ids
data = df.copy() #drop(columns=['id_rel_e', 'id_rel_p', 'rel_e', 'rel_p', 'id_e',
#        'id_p', 'err_e', 'err_p'])
data.QueryID = data.QueryID.astype(float)
list_doc_ids_raw = data.ListOfURLs[df.ListOfURLs.isnull()!=True].values
res = list()
for i in list_doc_ids_raw:
    res += i
all_doc_ids = res.copy()
# Get all the clicks
list_clicks_ids = data.URLID[df.URLID.isnull()!=True].values

# rho = probability of a doc to be clicked.
rho = len(list_clicks_ids)/len(all_doc_ids)
print(rho)

0.13445559411047547


### Step 4.2: Estimating the params of click models: Posistion-based Model

Prepare the data for training
    - assumption: we assume that all the queries have at least 3 docs shown.
    
    TODO: check if true

In [19]:
data = df.copy()
data.QueryID = data.QueryID.astype(float)

In [20]:
# Create the tables with all the params
n_docs = 6
unique_queries = data.QueryID[data.QueryID.isnull()!=True].astype(int).unique()
n_queries = len(unique_queries) 

In [21]:
start = time.time()

# Create query_doc empty pairs
query_doc_pairs = defaultdict()
for i in unique_queries:
    query_doc_pairs[i]=[]
    
# This code will give an error at the very last session ! -> move last session to the different bit.
sessions = data.SessionID.unique()[:-1]
for session in sessions:
    data_session = data[data.SessionID==session]
    click_ids =  data_session.URLID[data_session.URLID.isnull()!=True].values
    query_ids = data_session.QueryID[data_session.QueryID.isnull()!=True].values
    for query_id in query_ids:
        first_n_docs = data_session.ListOfURLs[data.QueryID==query_id].iloc[0]
        first_n_docs = np.array(list(map(int,first_n_docs))[:n_docs])
        # take index in the current data_session
        query_id_ind = data_session.QueryID[data_session.QueryID==query_id].index[0]
        flag = not math.isnan(data.URLID.iloc[query_id_ind+1])
        # if the next entry is click
        if flag:
            click_log = np.zeros(n_docs)
            query_id_ind+=1
            while flag==1:
                click_urlid = data.URLID.iloc[query_id_ind]
                # if click_urlid in first_n_docs then click is 1 on that position.
                doc_u_id = np.where(first_n_docs==click_urlid)
                click_log[doc_u_id]=1
                # increase the count
                query_id_ind +=1
                flag = not math.isnan(data.URLID.iloc[query_id_ind])
            # do updates
        else:
            click_log = np.zeros(n_docs)
            # do updates
            
        # Save query_id-click_log (=session-doc) pair for each query_id
        query_doc_pairs[query_id].append(click_log)
    
end = time.time()
print(f', but still kinda quick tho : seconds spent {end - start}, mins spent {(end - start)/60}')

, but still kinda quick tho : seconds spent 97.90545010566711, mins spent 1.6317575017611186


In [22]:
query_doc_pairs_old = query_doc_pairs.copy()
query_doc_pairs_old

defaultdict(None,
            {8: [array([0., 0., 0., 0., 0., 0.])],
             174: [array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([1., 1., 1., 0., 0., 0.]),
              array([1., 1., 1., 0., 1., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([1., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([0., 0., 0., 0., 0., 0.]),
              array([1., 0., 0., 0., 1., 0.]),
              array([0., 0., 0., 

Perform EM steps (update assignments ; update params):
    
    1) initialize alpha and gamma at random 
    2) For each time step:
        - Expecation: do not really have to do this step [?], what we want to see at the end: P(C|u) 
            - calculate P(C|u) for each u (u is from 1 to 3 = positions in the shown list)
            - " P(C|u) = P(A_uq|E,u)P(E|u) "
                
        - Maximization: update alpha and gamma params
        


In [23]:
alphas = np.random.rand(n_docs*n_queries).reshape((n_docs, n_queries))
gammas = np.random.rand(n_docs)

### Alphas 

In [24]:
assert unique_queries.shape[0] == alphas.shape[1], 'Error'

# for comparison :
alphas_old = alphas.copy()

In [25]:
start = time.time()

# Do the updates for alphas:

def train_alphas(alphas, gammas, query_doc_pairs, n_docs):
    # refer to alphas array with query_num as that it is how the are strored there:
    for query_num, query_id in enumerate(query_doc_pairs):
        for doc_u in range(n_docs):
            factor_1 = 1/len(query_doc_pairs[query_id])
            summ =  0
            for sessions_docs in query_doc_pairs[query_id]:
                click = sessions_docs[doc_u]
                summ += click + (1-click)*( (1-gammas[doc_u])*alphas[doc_u][query_num] ) / \
                                            (1-gammas[doc_u]*alphas[doc_u][query_num])
            alphas[doc_u][query_num] = factor_1*summ
    return alphas

alphas = train_alphas(alphas, gammas, query_doc_pairs, n_docs)

end = time.time()
print(f'seconds spent {end - start}, mins spent {(end - start)/60}')

seconds spent 1.0627906322479248, mins spent 0.01771317720413208


In [26]:
# Is that true that we ve changed every alpha ?
print('Is that true that we ve changed every alpha ? ->', not (alphas_old == alphas).any())
assert alphas_old.shape == alphas.shape, 'new shapes are incorrect'

Is that true that we ve changed every alpha ? -> True


### Gammas

We normalize by all the sessions.

In [27]:
all_sess = [ query_doc_pairs[idd] for idd in query_doc_pairs]
all_sess = reduce(lambda x,y: x+y, all_sess)

# for comparison :
gammas_old = gammas.copy()

In [28]:
start = time.time()

# Do the updates for gammas:

def train_gammas(alphas, gammas, query_doc_pairs, n_docs):
    for doc_u in range(n_docs):
        # refer to alphas array with query_num as that it is how the are strored there:
        summ =  0
        for query_num, query_id in enumerate(query_doc_pairs):
            factor_1 = 1 / len(all_sess)
            for sessions_docs in query_doc_pairs[query_id]:
                click = sessions_docs[doc_u]
                summ += click + (1-click)*( (1-alphas[doc_u][query_num])*gammas[doc_u] ) / \
                                            (1-gammas[doc_u]*alphas[doc_u][query_num])        
        gammas[doc_u] = factor_1 * summ
    
    return gammas

gammas = train_gammas(alphas, gammas, query_doc_pairs, n_docs)

end = time.time()
print(f'seconds spent {end - start}, mins spent {(end - start)/60}')

seconds spent 1.4281928539276123, mins spent 0.023803214232126873


In [29]:
# Test to see if we have all queries filled in
def check_sanity(l):
    if l==[]:
        return False
    else:
        return True
test = pd.Series(query_doc_pairs)
test_res = test.apply(check_sanity)
print('should be all true, coz otherwise we have queries with no sessions', np.unique(np.array(test_res)))

assert gammas_old.shape == gammas.shape, 'shapes are incorrect'

should be all true, coz otherwise we have queries with no sessions [ True]


In [30]:
gammas

array([0.87405009, 0.32226354, 0.31941428, 0.36206626, 0.94502001,
       0.29204346])

#### Training multiple times

In [31]:
gammas = np.random.rand(n_docs)
alphas = np.random.rand(n_docs*n_queries).reshape((n_docs,n_queries))

#  Training till convergence: 
n_epochs = 5
diff_alphas = [1]
diff_gammas = [1]

for i in range(n_epochs):
    gammas = train_gammas(alphas, gammas, query_doc_pairs, n_docs)
    alphas = train_alphas(alphas, gammas, query_doc_pairs, n_docs)
    
    #For plotting: checking convergence
    diff_alphas.append( diff_alphas[-1] - sum(sum(alphas)) )
    diff_gammas.append( diff_gammas[-1] - sum(gammas) )
    
    

In [33]:
import matplotlib.pyplot as plt

x = np.linspace(0, n_epochs+1, n_epochs+1)

fig, ax = plt.subplots(figsize=(7,5))
ax.plot(x,diff_gammas,marker='x')
fig.tight_layout()

In [34]:
gammas

array([0.89491988, 0.51267611, 0.28542979, 0.29143232, 0.770495  ,
       0.91864275])

### Step 5

Power analysis:
interleave and simulate clicks on every permutation for $k$ times. Then calculate winning prbability $p$. Do the Power Analysis to find minimum number of sample size $N$

In [35]:
# Variables


k = 50
rnd.seed(21)
#gammas = [0.484221138516365, 0.21930976273093877, 0.1581402982275157]
gammas_copy = gammas
#gammas = gammas_copy
epsilon = 0.05

p0 = 0.5
alphaN = 0.05
betaN = 0.1
za = 0.8289
zb = 0.8159


In [36]:
# if the probability of the PBM is higher than a ranomly generates number we assume a click happens

def sim_clicks(rankList):
    pList = np.ones(len(rankList))
    for n in range(len(pList)):
        if rankList[n] == 1:
            pList[n]*= (1-epsilon)*gammas[n]
        else:
            pList[n]*= epsilon*gammas[n]
    randP = np.random.uniform(size=len(pList))
    click = np.zeros(len(pList))
    for n in range(len(pList)):
        if pList[n] - randP[n] > 0:
            click[n] = 1
    return click



In [50]:
def random_click_model(rankList):
    clicks = np.ones(len(rankList))
    for idx in range(len(rankList)):
        clicks[idx] =  int(random.getrandbits(1))
    return clicks


In [51]:
def sample_size(p1):

    delta = np.absolute(p1-p0)
    N1 = np.power(((za - alphaN*np.sqrt(p0*(1.0-p0))+zb-betaN*np.sqrt(p1*(1.0-p1)))/delta),2)
    N = np.ceil(N1 + (1/delta))
    return N

In [52]:
import random
def poweranal(tup,clickmodel=sim_clicks):
    winsTDE = 0
    winsPE = 0
    winsTDP = 0
    winsPP = 0
    for n in range(k):
        rankTD = team_draft(tup,int(random.getrandbits(1)))
        rankP = probabelistic_interleaving(tup)

        relTD = np.zeros(len(rankTD))
        relP = np.zeros(len(rankP))
        for m in range(len(rankTD)):
            line = rankTD[m]
            relTD[m] = line[1]
        for m in range(len(rankP)):
            line = rankP[m]
            relP[m] = line[1]

        clicksTDE = 0
        clicksTDP = 0
        clicksPE = 0
        clicksPP = 0
        while clicksTDE==clicksTDP or clicksPE==clicksPP:
            clicksTD = clickmodel(relTD)
            clicksP = clickmodel(relP)
            for m in range(len(clicksTD)):
                lineTD = rankTD[m]
                lineP = rankP[m]
                if clicksTD[m] == 1 and lineTD[2] == 'E':
                    clicksTDE +=1
                if clicksTD[m] == 1 and lineTD[2] == 'P':
                    clicksTDP +=1
                if clicksP[m] == 1 and lineP[2] == 'E':
                    clicksPE +=1
                if clicksP[m] == 1 and lineP[2] == 'P':
                    clicksPP +=1
            if clicksTDE>clicksTDP: 
                winsTDE+=1
            if clicksTDE<clicksTDP: 
                winsTDP+=1 
            if clicksPE>clicksPP:   
                winsPE+=1 
            if clicksPE<clicksPP:   
                winsPP+=1 

    pTD =  winsTDE/(winsTDE+winsTDP) if  winsTDP+winsTDE>0 else 0.5
    pP = winsPE/(winsPE+winsPP) if winsPP+winsPE>0  else 0.5
    
    # calcutale N
    
    NTD = sample_size(pTD)
    NP = sample_size(pP)
    
    return NTD,pTD, NP,pP

    

In [57]:
team_table = {}
prob_table = {}
for score,relevance_list in binned.items():
    team_table[score] = []
    prob_table[score] = []
    for relevance in relevance_list:
        permutations = create_possible_permutations(relevance)
        for doclist in permutations:
            team_sample,pTD,prob_sample,pP = poweranal(doclist,random_click_model)
            team_table[score].append(team_sample)
            prob_table[score].append(prob_sample)

            
print("Random click model team draft table")
for key,val in team_table.items():
    if not val:continue
    l = [v for v in val if not v==float("Inf")]
    
    print(f'{key-0.05:.2f}-{key}: min:{min(l)} median:{np.median(l)} max:{max(l)}')

    
print()
print("Position based model probabelistic table")
for key,val in prob_table.items():
    if not val:continue
    l = [v for v in val if not v==float("Inf")]    
    print(f'{key-0.05:.2f}-{key}: min:{min(l)} median:{np.median(l)} max:{max(l)}')

    
print()  
team_table = {}
prob_table = {}
for score,relevance_list in binned.items():
    team_table[score] = []
    prob_table[score] = []
    for relevance in relevance_list:
        permutations = create_possible_permutations(relevance)
        for doclist in permutations:
            team_sample,pTD,prob_sample,pP = poweranal(doclist)
            team_table[score].append(team_sample)
            prob_table[score].append(prob_sample)

            

print("Position based model team draft table")
for key,val in team_table.items():
    if not val:continue
    l = [v for v in val if not v==float("Inf")]
    
    print(f'{key-0.05:.2f}-{key}: min:{min(l)} median:{np.median(l)} max:{max(l)}')

    
print()
print("Position based model probabilistic table")
for key,val in prob_table.items():
    if not val:continue
    l = [v for v in val if not v==float("Inf")]    
    print(f'{key-0.05:.2f}-{key}: min:{min(l)} median:{np.median(l)} max:{max(l)}')
    

/home/joseph/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  after removing the cwd from sys.path.
/home/joseph/.local/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  """


Random click model team draft table
0.05-0.1: min:21.0 median:135.0 max:47068.0
0.10-0.15: min:13.0 median:61.5 max:14310.0
0.20-0.25: min:15.0 median:176.0 max:44383.0
0.25-0.3: min:17.0 median:136.0 max:41777.0
0.30-0.35: min:13.0 median:73.0 max:55597.0
0.35-0.4: min:20.0 median:175.0 max:44383.0
0.40-0.45: min:30.0 median:453.5 max:12146.0
0.45-0.5: min:27.0 median:358.0 max:49832.0
0.55-0.6: min:18.0 median:204.0 max:52675.0
0.60-0.65: min:12848.0 median:12848.0 max:12848.0

Position based model  probabelistic table
0.05-0.1: min:16.0 median:289.0 max:52675.0
0.10-0.15: min:20.0 median:257.0 max:44383.0
0.20-0.25: min:18.0 median:243.0 max:41777.0
0.25-0.3: min:32.0 median:225.5 max:36801.0
0.30-0.35: min:19.0 median:207.0 max:49832.0
0.35-0.4: min:25.0 median:553.0 max:55597.0
0.40-0.45: min:32.0 median:133.0 max:2620.0
0.45-0.5: min:14.0 median:106.0 max:52675.0
0.55-0.6: min:18.0 median:111.0 max:41777.0
0.60-0.65: min:1035.0 median:1035.0 max:1035.0

Position based model team 

The results can be observed in the previous window.

Result Analysis:
 We observe an inverse correlation between the $\Delta ERR$ score and the sample size results. The sample size to achieve required significance decreases as the $\Delta ERR$ increases.
 Due to the higher $\Delta ERR$, algorithm $E$ outperforms $P$ with a higher percentage, and thus significance is reached after less impressions.
 The parameter $\gamma$ derived in the Position Based Model dominates document selection. The first presented document has a much higher chance of being selected than any other document. If the first document is considered relevant, we will most likely observe a click. The probability of being clicked decreases at every lower position. Because we can only have one document at the first position, that algorithm will have a higher winning chance, however, the starting algorithm is chosen at random for every impression, and thus this advantage should level out. If both models provide relevant documents, it will be harder to discern between the better algorithm, hence the higher number of impressions required.  A higher choice of parameter $\epsilon$ will lead to a higher sample size since irrelevant documents will achieve a higher click probability. The parameter k determines the number of interleaving experiments we run, if k is set appropriately the win probability should converge to the correct value. We picked k=50 after empirical research.
The obtained results show that the required minimum sample size decreases with higher $\Delta ERR$. 

The results from the random click model are not of any relevance as they do not take any crucial variables in account(document relevance, ranking) and thus would lead to both algorithms haveing approximately equal performance, hence the high values. 





In the following section suggest certain improvements on the experimental setup for further research.

different click model
The implemented Position Based Model is but one of many attempts to model user behaviour.
Factors like the time spend on each page are not taken into account. The user can find a satisfying answer on the first page and only use the second to confirm. Or the user could click several pages and still not find the needed information. A third scenario is that the user does not click at all but finds the required information in the page summary.
These are all variables we could take into account to improve our model to simulate more accurate user behaviour. If we are able to model this behaviour better, we can more accurately determine the better algorithm, which ofcourse is our final goal.

represent alpha better
In this experiment we did not consider real documents and queries therefore the $\alpha$ parameter had to be replaced with a simpler $\epsilon$. This simplifies the experiment. A more elaborated approach is recommended.

One last suggestion for further research is to use a representative set of training-data. Different target groups behave differently and have different expectations and behaviours when using a search engine. Specifying a target group and using specific trainingdata will give more focused information about the performance of the new algorithm.
